spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@leisurethat_high?TNS_ADMIN=./src/main/resources/wallet
    username: LEISURETHAT
    password: OracleOracle123
